### ISSUE TITLE
Could you please provide more guidance on reproducing Aachen for SIFT? 

### ISSUE THREAD

**Issue by GabbySuwichaya** [vdvchen/SGMNet#3]
Hi!  I would like to ask for guidance on reproducing Aachen for SIFT and SGMNet+SIFT? 

At a starter, I have tried to run MNN+SIFT for Aachen day-night...but I get a much worse result for 8196 keypoints... 23.5 / 33.7 / 41.8
I am guessing that maybe because I am using SIFT instead of RootSIFT... But I am not sure about other settings that could be different...  

So, as I saw the result of SGMNet+SIFT as well as MNN+SIFT on both papers and on https://www.visuallocalization.net/details/17655/, I am wondering how to reproduce them (especially Table 4. in the paper)... 
 
Could you please share the setting? I would like to learn how to get a similar result... 

So I would like to scope down my question as follows:
-  Firstly, it is RootSIFT not SIFT...where self.root == True (in  https://github.com/vdvchen/SGMNet/blob/main/components/extractors.py#L43 ) ? Is that correct? Do you have to further normalize the features (to keep the norm of feature dimension to 1) ?
- Did you restrict image size?  For example, in D2-Net, the maximum size was restricted to 1600 ? Did you do something like that too? 
- For `MNN+SIFT`, is there any thresholding applied for MNN matching? 
- Is the setting for SGMNet+SIFT for Aachen Day-Night similar to the following?  Also, as I read the name ...rootsift8k_upright_512_0.2_SGMNet... What do you mean by 512 and 0.2? 
```
matcher:
  name: SGM
  model_dir: ../weights/sgm/root
  seed_top_k: [256,256]
  seed_radius_coe: 0.01
  net_channels: 128
  layer_num: 9
  head: 4
  seedlayer: [0,6]
  use_mc_seeding: True
  use_score_encoding: False
  conf_bar: [1.11,0.1] #set to [1,0.1] for sp
  sink_iter: [10,100]
  detach_iter: 1000000
  p_th: 0.2
```
- Also, is the setting for SG+SIFT for Aachen Day-Night similar to ?
```
matcher:
  name: SG
  model_dir: ../weights/sg/root
  net_channels: 128
  layer_num: 9
  head: 4
  use_score_encoding: True
  sink_iter: [100]
  p_th: 0.2
```
